name: Workspace Example

on:
  push:
    branches: [ main ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

#Set the output as environment variable and use it in job2
      - name: Write data to output
        id: set_output
        run: |
          echo "HELLO_WORLD=$(python helloworld.py)" >> $GITHUB_OUTPUT
#          echo "::set-output name=HELLO_WORLD::$(python helloworld.py)" 
       
    outputs:
      hello_world: ${{ steps.set_output.outputs.HELLO_WORLD }}


  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

#Use the output from job1
#env: to use environment variable inside pov.py script

      - name: Run Python data
        env:
          HELLO_WORLD: ${{ needs.job1.outputs.hello_world }}
        run: |
          python pov.py