name: Workspace Example

on:
  push:
    branches: [ main ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Write data to file
        run: |
          python3 helloworld.py 
          echo "HELLO_WORLD=$(python helloworld.py)" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print data
        run: echo "${{ env.HELLO_WORLD }}"

