name: Workspace Example

on:
  push:
    branches: [ main ]
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write data to file
        run: echo "Hello, world!" > file.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read data from file
        run: cat file.txt
